:- module(terminalNames,
	[
		terminalName/2
	]).

terminalName(t('stringliteral'), 'STRING').
terminalName(t('='), 'ASIGNACION').
terminalName(t('++'), 'INCREMENTOR').
terminalName(t('--'), 'DECREMENTOR').
terminalName(t('charliteral'), 'CARACTER').
terminalName(t('intliteral'), 'ENTERO').
terminalName(t('idclase'), 'IDENTIFICADOR_DE_CLASE').
terminalName(t('idmetvar'), 'IDENTIFICADOR_DE_METODO_O_VARIABLE').
terminalName(t('>'), 'MAYOR').
terminalName(t('>='), 'MAYOR_IGUAL').
terminalName(t('<'), 'MENOR').
terminalName(t('<='), 'MENOR_IGUAL').
terminalName(t('!'), 'NEGACION').
terminalName(t('!='), 'DISTINTO').
terminalName(t('=='), 'COMPARACION').
terminalName(t('+'), 'SUMA').
terminalName(t('-'), 'RESTA').
terminalName(t('*'), 'PRODUCTO').
terminalName(t('/'), 'DIVISION').
terminalName(t('%'), 'MODULO').
terminalName(t('&&'), 'AND').
terminalName(t('||'), 'OR').
terminalName(t(')'), 'PARENTESIS_CIERRA').
terminalName(t('('), 'PARENTESIS_ABRE').
terminalName(t('{'), 'LLAVE_ABRE').
terminalName(t('}'), 'LLAVE_CIERRA').
terminalName(t(';'), 'PUNTO_Y_COMA').
terminalName(t(','), 'COMA').
terminalName(t('.'), 'PUNTO').
%terminalName(t(''), EOF).
terminalName(t('class'), 'CLASS_PR').
terminalName(t('extends'), 'EXTENDS_PR').
terminalName(t('static'), 'STATIC_PR').
terminalName(t('dynamic'), 'DYNAMIC_PR').
terminalName(t('void'), 'VOID_PR').
terminalName(t('boolean'), 'BOOLEAN_PR').
terminalName(t('char'), 'CHAR_PR').
terminalName(t('int'), 'INT_PR').
terminalName(t('string'), 'STRING_PR').
terminalName(t('public'), 'PUBLIC_PR').
terminalName(t('private'), 'PRIVATE_PR').
terminalName(t('if'), 'IF_PR').
terminalName(t('else'), 'ELSE_PR').
terminalName(t('for'), 'FOR_PR').
terminalName(t('return'), 'RETURN_PR').
terminalName(t('this'), 'THIS_PR').
terminalName(t('new'), 'NEW_PR').
terminalName(t('null'), 'NULL_PR').
terminalName(t('true'), 'TRUE_PR').
terminalName(t('false'), 'FALSE_PR').